# Site settings
title: "Matt&Meg"
email: contact@mattmeg.com
description: "Our family blog. Born in Chicago."
baseurl: ""
url: "http://mattmeg.com"
twitter_username: matthewcyan
github_username: mattborn

# Build settings
markdown: kramdown
permalink: /:categories/:title

# Prose settings
prose:
  rooturl: "_posts"
  siteurl: "http://mattmeg.github.io/"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          placeholder: "Choose Layout"
          options:
            - name: "Post"
              value: "post"
            - name: "Maely"
              value: "maely"